name: Python Package Using Anaconda

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: muskit-env
          environment-file: env.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pytest
